import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black
        text-white`}
      >
        <header className="py-4">
          <nav className="flex justify-between items-center container mx-auto">
            <Link href="/" className="text-2xl font-bold">
              Home
            </Link>
            <div className="space-x-8">
              <Link href="/performance" className="text-lg font-light">
                Performance
              </Link>
              <Link href="/reliability" className="text-lg font-light">
                Reliability
              </Link>
              <Link href="/scala" className="text-lg font-light">
                Scala
              </Link>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
